rootProject.name = "CustomCrops"
include(":api")
include(":plugin")
include(":compatibility")
include(":compatibility-asp-r1")
//include(":compatibility-asp-r2")
include(":compatibility-oraxen-r1")
include(":compatibility-oraxen-r2")
include(":compatibility-nexo-r1")
include(":compatibility-itemsadder-r1")
include(":compatibility-itemsadder-r2")
include(":compatibility-crucible-r1")
include(":compatibility-craftengine-r1")
